name-template: "Release v$NEXT_VERSION"
tag-template: "v$NEXT_VERSION"

# Plantilla del draft release: filtra solo por labels
template: |
  ## 🚀 Features
  $CHANGES{label=feature}

  ## 🐛 Bug Fixes
  $CHANGES{label=bug}

  ## 📝 Documentation
  $CHANGES{label=docs}

# Categorías opcionales para organizar PRs
categories:
  - title: "🚀 Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "📝 Documentation"
    labels: ["docs"]

# Cómo se ve cada línea del changelog
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
